#################################
#   Transparency / Opacity      #
#################################
opacity-rule = [
  "95:class_g = 'st-256color' && focused",
  "85:class_g = 'st-256color' && !focused"
];

#################################
#           Fading              #
#################################

fading = true
fade-in-step = 0.05;
fade-out-step = 0.05;
