# Show Hidden
# Enable it with keys zh
set show_hidden false

# colorscheme: 
# default, jungle, snow, solarized
set colorscheme default

#Image render
set preview_images true
set preview_images_method ueberzug
