# Show Hidden
set show_hidden true

# Devicons
#
# Install a nerdfont and do the following
# git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
#default_linemode devicons

# colorscheme: 
# default, jungle, snow, solarized
set colorscheme solarized

set viewmode miller
set column_ratios 3
set draw_borders true

set vcs_aware true

# State of the four backends git, hg, bzr, svn. The possible states are
# disabled, local (only show local info), enabled (show local and remote
# information).
set vcs_backend_git enabled
set vcs_backend_hg disabled
set vcs_backend_bzr disabled
set vcs_backend_svn disabled

set preview_images true
set preview_images_method ueberzug


# Draw the status bar on top of the browser window (default: bottom)
set tatus_bar_on_top false

set draw_progress_bar_in_status_bar true

