[global]
username = "username"
password = "password"

device_type = "computer"

backend = "pulseaudio"
device_name = "PC"
bitrate = 320

volume_normalisation = true
initial_volume = "90"

# A command that gets executed in your shell after each song changes.
on_song_change_hook = "command_to_run_on_playback_events"
