# Statusbar loop
while true; do
	~/.local/bin/statusBar.sh
	sleep 1s
done &

# Avoid battery saver screen
xset -dpms
xset s off

xwallpaper --stretch ~/.local/share/wallpaper/bonsai_tree.jpg
picom &

exec dwm
