opacity-rule = [
 "95:class_g = 'st-256color'",
];

# Blur
blur:
{
  method = "none";
  kern = "3x3box";
}

# Fading
fading = true
fade-in-step = 0.05;
fade-out-step = 1.0;

# General
backend = "xrender";
vsync = true
refresh-rate = 60

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
